# Generated by Django 2.1 on 2018-08-18 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('c_class', models.CharField(default='', max_length=50, verbose_name='班级')),
                ('p_number', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('group', models.CharField(default='', max_length=50, verbose_name='社团名称')),
                ('signtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='报名时间')),
                ('message', models.CharField(default='', max_length=500, verbose_name='建议')),
            ],
            options={
                'verbose_name_plural': '报名表',
                'verbose_name': '报名表',
            },
        ),
    ]
