# Generated by Django 2.1 on 2018-08-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='message',
            field=models.TextField(default='', verbose_name='建议'),
        ),
    ]
